/*

COMPLETE THIS FILE WITH JAVASCRIPT CODE, AND ANSWER THE QUESTIONS BELOW:

Q1: What is the purpose of the following line in the CSS file, and what does it do?
    left: calc(50% - 62px)
    (0.5 mark)

A1: WRITE YOUR ANSWER HERE.

------------------------------------------------------------------------------------------

Q2: The play() method does not take any arguments. How does it know which image the player has selected?
    (0.5 mark)

A2: WRITE YOUR ANSWER HERE.

------------------------------------------------------------------------------------------

Q3: What can you say about the height of the #computer_choice element?
    How much is it? What does the element contain? Does the height make sense?
    If you could change it, what would you change it to, and why?
    Explain your answer.
    (0.5 mark)

A3: WRITE YOUR ANSWER HERE.

------------------------------------------------------------------------------------------

Q4: We want to change the play function so that it now takes an argument.
    We expect the argument to be an event object, like the ones generated by event listeners.
    Which changes would you make to the code? Be as descriptive as possible.
    (1.5 marks)

A4: WRITE YOUR ANSWER HERE.

------------------------------------------------------------------------------------------

WRITE YOUR CODE BELOW OUTSIDE OF THE COMMENT.

*/

function play() {
    // complete this function
}

// add code