/*

COMPLETE THIS FILE WITH JAVASCRIPT CODE, AND ANSWER THE QUESTIONS BELOW:

Q1: What is the purpose of the following line in the CSS file, and what does it do?
    left: calc(50% - 62px)
    (0.5 mark)

A1: WRITE YOUR ANSWER HERE.
it keeps the content centered in its own div
------------------------------------------------------------------------------------------

Q2: The play() method does not take any arguments. How does it know which image the player has selected?
    (0.5 mark)

A2: WRITE YOUR ANSWER HERE.
it doesnt 
it will once you add the event listener and the paramenter to the play() function
------------------------------------------------------------------------------------------

Q3: What can you say about the height of the #computer_choice element?
    How much is it? What does the element contain? Does the height make sense?
    If you could change it, what would you change it to, and why?
    Explain your answer.
    (0.5 mark)

A3: WRITE YOUR ANSWER HERE.
it is 200px and relative to the width of the image
the element contains the image of the computer's choice 
i would change it to the height of the picture inside so it doesnt take up so much space
------------------------------------------------------------------------------------------

Q4: We want to change the play function so that it now takes an argument.
    We expect the argument to be an event object, like the ones generated by event listeners.
    Which changes would you make to the code? Be as descriptive as possible.
    (1.5 marks)

A4: WRITE YOUR ANSWER HERE.

add parameter to the play() function and call on that parameter in the function
------------------------------------------------------------------------------------------

WRITE YOUR CODE BELOW OUTSIDE OF THE COMMENT.

*/
function getRand() {
    computer_choice = (Math.random() * 3);
    console.log(computer_choice);
    return computer_choice;
}

function play() {
    computer_choice = getRand();
    
    if (computer_choice < 1) {
        computer_choice = "computer_rock";
    } else if (computer_choice < 2) {
        computer_choice = "computer_paper";
    } else {
        computer_choice = "computer_scissors";
    }
    console.log(computer_choice);


    for (let u in document.getElementById("computer_choice").children) {
        try {if (document.getElementById("computer_choice").children[u].style.display === "block") {
            document.getElementById("computer_choice").children[u].style.border = "10px solid transparent";
            document.getElementById("computer_choice").children[u].style.display = "none";
        }} catch (error) {
            console.log(error);}
    }

    for (let u in document.getElementById("computer_choice").children) {
        if (document.getElementById("computer_choice").children[u].id === computer_choice) {
            document.getElementById("computer_choice").children[u].style.border = "10px solid black";
            document.getElementById("computer_choice").children[u].style.display = "block";
        }
        
    }
    
    document.getElementById("computer_choice").style.border = "10px solid transparent";
    document.getElementById("computer_choice").style.display = "block";

    let x = null;
   
    for (let i = 0; i < 3; i++) {
        if (document.getElementById("player_choice").children[i].classList.contains("selected")){
            x = document.getElementById("player_choice").children[i].id;
        }
        
    }

    if (x === "rock" && computer_choice === "computer_rock" || x === "paper" && computer_choice === "computer_paper" || x === "scissors" && computer_choice === "computer_scissors") {
        return 0;};
    if (x === "rock" && computer_choice === "computer_paper" || x === "paper" && computer_choice === "computer_scissors" || x === "scissors" && computer_choice === "computer_rock") {
        return -1;};
    if (x === "rock" && computer_choice === "computer_scissors" || x === "paper" && computer_choice === "computer_rock" || x === "scissors" && computer_choice === "computer_paper") {
        return 1;};
    
    }

function checkWinner(Result) {
    if (Result === 0) {
        document.getElementById("result").textContent = "Tie";
        console.log("tie");
    } else if (Result === 1) {
        document.getElementById("result").textContent = "You Win";
        console.log("win");
    } else if (Result === -1){
        document.getElementById("result").textContent = "You Lose";
        console.log("lose");
    }
    document.getElementById("play-again").style.display = "block";
}

document.addEventListener("DOMContentLoaded", () => {
    document.getElementById("play-again").addEventListener("click", (event) => {
        document.getElementById("play-again").style.display = "none";
        document.getElementById("rock").removeAttribute("class", "selected");
        document.getElementById("paper").removeAttribute("class", "selected");
        document.getElementById("scissors").removeAttribute("class", "selected");
        
        document.getElementById("computer_choice").style.border = "10px solid transparent";
        document.getElementById("computer_choice").style.display = "none";

        document.getElementById("result").textContent = "";
    
    });
    let rock = document.getElementById("rock");
    let paper = document.getElementById("paper");
    let scissors = document.getElementById("scissors");
    
    rock.addEventListener("click", (event) => {
        if (document.getElementById("play-again").style.display !== "block") {
            rock.setAttribute("class", "selected");
            paper.removeAttribute("class", "selected");
            scissors.removeAttribute("class", "selected");
            winner = play();
            checkWinner(winner);}

        });

    paper.addEventListener("click", (event) => {
        if (document.getElementById("play-again").style.display !== "block") {
            rock.removeAttribute("class", "selected");
            paper.setAttribute("class", "selected");
            scissors.removeAttribute("class", "selected");
            winner = play();
            checkWinner(winner);}
        });

    scissors.addEventListener("click", (event) => {
        if (document.getElementById("play-again").style.display !== "block"){
            rock.removeAttribute("class", "selected");
            paper.removeAttribute("class", "selected");
            scissors.setAttribute("class", "selected");
            winner = play();
            checkWinner(winner);}
        });
    
    

});